import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local'

const moonet = localFont({
  src: "./fonts/moonet.otf",
  variable: "--font-moonet",  // gives you a CSS var
  display: "swap",
  // weight: "400", // optional, add if you want to be explicit
  // style: "normal",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${moonet.variable} antialiased bg-black `}
      >
        {children}
      </body>
    </html>
  );
}
